[versions]
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
kotlin = "2.2.21"
android = "8.13.1"
activityCompose = "1.12.0"
composeBom = "2025.12.00"
coreKtx = "1.17.0"
junit = "4.13.2"
kotlinxDatetime = "0.7.1-0.6.x-compat"
lifecycleRuntimeKtx = "2.10.0"
loadersGears = "0.4.0"
loadersJigsaw = "0.2.0"
loadersTrigonometry = "0.1.0"
mockitoKotlin = "6.1.0"
mockitoInline = "5.2.0"
navigationCompose = "2.9.6"
ktlint = "14.0.1"
gradleNexusPublish = "2.0.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
loaders-gears = { module = "com.mitteloupe.loaders:loaders-gears", version.ref = "loadersGears" }
loaders-jigsaw = { module = "com.mitteloupe.loaders:loaders-jigsaw", version.ref = "loadersJigsaw" }
loaders-trigonometry = { module = "com.mitteloupe.loaders:loaders-trigonometry", version.ref = "loadersTrigonometry" }
material3 = { module = "androidx.compose.material3:material3" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui = { module = "androidx.compose.ui:ui" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
gradleNexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexusPublish" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
